// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientDoctorConsultation.Infrastructure.Persistence.Context;

#nullable disable

namespace PatientDoctorConsultation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529103150_AddDoctorDiscoveryFoundation")]
    partial class AddDoctorDiscoveryFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Admin.Models.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("IX_AdminAuditLogs_AdminUserId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AdminAuditLogs_CreatedAt");

                    b.HasIndex("TargetEntityId")
                        .HasDatabaseName("IX_AdminAuditLogs_TargetEntityId");

                    b.ToTable("AdminAuditLogs", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ConsultationFeeSnapshot")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ConsultationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConsultationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MeetingEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<string>("MeetingRoomId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("MeetingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentConsultationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ConsultationNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Consultations_ConsultationNumber");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Consultations_DeletedAt_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Consultations_DoctorId");

                    b.HasIndex("ParentConsultationId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Consultations_PatientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Consultations_Status");

                    b.HasIndex("ScheduledDate", "DoctorId")
                        .HasDatabaseName("IX_Consultations_ScheduledDate_DoctorId");

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Consultation.Models.ConsultationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("IX_ConsultationStatusHistories_ConsultationId");

                    b.ToTable("ConsultationStatusHistories", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Doctor.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CityNormalized")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClinicAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("ConsultationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("HospitalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPubliclyVisible")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("LanguagesSpoken")
                        .HasColumnType("text[]");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SpecializationNormalized")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalConsultations")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("IX_Doctors_ApprovalStatus");

                    b.HasIndex("CityNormalized")
                        .HasDatabaseName("IX_Doctors_CityNormalized");

                    b.HasIndex("ConsultationFee")
                        .HasDatabaseName("IX_Doctors_ConsultationFee");

                    b.HasIndex("ExperienceYears")
                        .HasDatabaseName("IX_Doctors_ExperienceYears");

                    b.HasIndex("IsPubliclyVisible")
                        .HasDatabaseName("IX_Doctors_IsPubliclyVisible");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Doctors_LicenseNumber")
                        .HasFilter("\"LicenseNumber\" IS NOT NULL");

                    b.HasIndex("SpecializationNormalized")
                        .HasDatabaseName("IX_Doctors_SpecializationNormalized");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Doctors_UserId");

                    b.HasIndex("City", "Specialization")
                        .HasDatabaseName("IX_Doctors_City_Specialization");

                    b.HasIndex("IsPubliclyVisible", "ApprovalStatus")
                        .HasDatabaseName("IX_Doctors_Discovery_Eligibility");

                    b.HasIndex("IsPubliclyVisible", "ApprovalStatus", "SpecializationNormalized", "CityNormalized")
                        .HasDatabaseName("IX_Doctors_Discovery_Composite");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Doctor.Models.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DoctorAvailabilities_DoctorId");

                    b.HasIndex("DoctorId", "DayOfWeek")
                        .HasDatabaseName("IX_DoctorAvailabilities_DayOfWeek");

                    b.ToTable("DoctorAvailabilities", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Patient.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProfileCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Patients_DeletedAt");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Patients_UserId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Prescription.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneralInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Prescriptions_ConsultationId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Prescription.Models.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems", (string)null);
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Admin.Models.AdminAuditLog", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Auth.Models.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AdminAuditLogs_Users_AdminUserId");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Doctor.Models.DoctorAvailability", null)
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Consultations_DoctorAvailabilities_AvailabilityId");

                    b.HasOne("PatientDoctorConsultation.Modules.Doctor.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Consultations_Doctors_DoctorId");

                    b.HasOne("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", "ParentConsultation")
                        .WithMany("FollowUps")
                        .HasForeignKey("ParentConsultationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Consultations_Consultations_ParentConsultationId");

                    b.HasOne("PatientDoctorConsultation.Modules.Patient.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Consultations_Patients_PatientId");

                    b.Navigation("ParentConsultation");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Consultation.Models.ConsultationStatusHistory", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", "Consultation")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultationStatusHistories_Consultations_ConsultationId");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Doctor.Models.DoctorAvailability", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Doctor.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Prescription.Models.Prescription", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", null)
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Prescriptions_Consultations_ConsultationId");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Prescription.Models.PrescriptionItem", b =>
                {
                    b.HasOne("PatientDoctorConsultation.Modules.Prescription.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PrescriptionItems_Prescriptions_PrescriptionId");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Consultation.Models.Consultation", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Doctor.Models.Doctor", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("PatientDoctorConsultation.Modules.Prescription.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
