<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PatientDoctorConsultation.Modules.Prescription</AssemblyName>
    <RootNamespace>PatientDoctorConsultation.Modules.Prescription</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Shared/Shared.csproj" />
    <ProjectReference Include="../../Infrastructure/Infrastructure.csproj" />
    <ProjectReference Include="../Shared/Modules.Shared.csproj" />
    <ProjectReference Include="../Consultation/Modules.Consultation.csproj" />
    <ProjectReference Include="../Doctor/Modules.Doctor.csproj" />
    <ProjectReference Include="../Patient/Modules.Patient.csproj" />
  </ItemGroup>

</Project>
